### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by SSanjos** [cami-la/debugging-java#3]
Olá Camila, boa tarde! Estou no módulo Debugging Java, estava escrevendo um código como exercício e estou com esse erro que não consegui resolver.

Poderia me ajudar?

![image](https://user-images.githubusercontent.com/99223663/166492637-a47809b1-3ec3-4cd6-8465-5274a2f0cd44.png)

![image](https://user-images.githubusercontent.com/99223663/166493044-d070b9b4-99a0-479b-8c86-e80339dc2d44.png)

**Comment by SSanjos** [comment]
Opa! Resolvido aqui!

**Comment by cami-la** [comment]
Oi, amigo. Boa tarde. (:
Fico feliz em saber que você conseguiu resolver.
Mas bem simples, o `switch-case` é para situações mais simples, tá? Quando precisa de verificações mais robustas, usa o `if-else` que funciona muito bem. 

Aqui na documentação da própria Oracle, tem uns exemplos bem legais:
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/switch.html

Qualquer dúvida, fico à disposição!

**Comment by SSanjos** [comment]
Obrigado Camila!
